<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2010-02-12 13:34

return array(
	'tx_t3notes_auth' => t3lib_extMgm::extPath('t3notes') . 'lib/class.tx_t3notes_auth.php',
);
?>